"""record provider and mode on runs

Revision ID: 22a9ea4d64f6
Revises: f7e05f82a5b2
Create Date: 2026-07-23 15:16:10.285873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a9ea4d64f6'
down_revision: Union[str, None] = 'f7e05f82a5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('mode', sa.String(length=16), nullable=True))
    op.add_column('runs', sa.Column('provider_name', sa.String(length=32), nullable=True))
    op.add_column('runs', sa.Column('model', sa.String(length=128), nullable=True))
    op.add_column('runs', sa.Column('identity', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'identity')
    op.drop_column('runs', 'model')
    op.drop_column('runs', 'provider_name')
    op.drop_column('runs', 'mode')
    # ### end Alembic commands ###
