"""runs and steps tables

Revision ID: f7e05f82a5b2
Revises: 
Create Date: 2026-07-23 11:31:13.761302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7e05f82a5b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_status_heartbeat', 'runs', ['status', 'heartbeat_at'], unique=False)
    op.create_index('ix_runs_tenant_session', 'runs', ['tenant_id', 'session_id'], unique=False)
    op.create_index('ix_runs_tenant_status', 'runs', ['tenant_id', 'status'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idx', name='uq_steps_run_idx')
    )
    op.create_index('ix_steps_run_idx', 'steps', ['run_id', 'idx'], unique=False)
    op.create_index('ix_steps_tenant_kind', 'steps', ['tenant_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_steps_tenant_kind', table_name='steps')
    op.drop_index('ix_steps_run_idx', table_name='steps')
    op.drop_table('steps')
    op.drop_index('ix_runs_tenant_status', table_name='runs')
    op.drop_index('ix_runs_tenant_session', table_name='runs')
    op.drop_index('ix_runs_status_heartbeat', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
